### ISSUE TITLE
Poor security/validation during account signup

### ISSUE THREAD

**Issue by KorenSpell** [WVU-CS230-2023-01-Group02/bottomText#47]
The Issue:
When signing up for an account, there is nothing stopping you from not adding a name, student/professor status, or even a valid email. This is an issue because users could scam others using our site to sell fake textbooks or give blatantly false information about courses and we would have no way of tracing them. We could remove the account from the database, but that would treat the symptom, not the illness.

How to Replicate: (This example follows the exact steps I used to find the issue)
- Open the side bar on the home page of the website
- Click sign up
- Leave all fields blank except Email and Password
- Enter the following values:
- Email: email@fake.fake
- Password: eeeeee
- You now have an account that you can log back in with that has no ties to the user whatsoever
- **Important note: this is obviously not a real email involving anyone's personal info, it is completely fake**

Submitted by,
   Koren Spell

**Comment by adsarver** [comment]
Fixed

Added minimum password requirements
Added field checks
Added .edu check

Unfortunately, the fake email is just as possible to be real as it is fake. Anyone could buy a domain name like that and host their own email server, but I added a check so we only allow .edu emails
