### ISSUE TITLE
User logged in status is revoked when leaving user page to home page

### ISSUE THREAD

**Issue by HunterCriss** [WVU-CS230-2023-01-Group02/bottomText#72]
---
Hunter Criss
Sometimes user is logged out when leaving the Users Page
---

**Description of Bug**
When logging in the user data is successfully displayed on the Users Page however, logged-in status is revoked when navigating away. This occurs when going directly to the home layout but not when going directly to a listing query. The home layout will prompt the user to sign in again indicating the user has been logged out. Additionally navigating to the search page after visiting the home page does not allow listing creation to occur.

**To Reproduce**
1. Login through the login modal.
2. On successful login a route to the user page with user data specific to the account will be displayed.
3. Click the bottom text logo routing back to the home page.
4. The sidebar popup will prompt the user to log in again rather than the normal account holder options.
5. Search for a class through the search field.
6. Attempt to create a new listing using the new listing button.
7. The user will be asked to log in again indicating a revoked login status.

**Expected behavior**
The user should see a separate sidebar in the home layout after logging in. The user should also be able to write new listings about courses after login into an account. The proper modal view should be displayed.

**Comment by adsarver** [comment]
I'm unable to recreate this, are you on an up-to-date version of auth.service?
