### ISSUE TITLE
User logged in but cannot access dashboard if the user goes back one page instead of refreshing the page

### ISSUE THREAD

**Issue by FA6363** [WVU-CS230-2023-01-Group02/bottomText#80]
---
Faisal Alogaibi
User logged in but cannot access dashboard if the user goes back one page instead of refreshing the page
---

**Description of Bug**
When a user logs in from the results page, and goes back one page, the dashboard still displays that the user needs to log in and the account cannot be accessed. If the user goes forward one page to the results page, the user can add a new listing, which confirms that the user is indeed logged in.

**To Reproduce**
1. Go to the bottomText website
2. Make sure that you are signed-out
3. Navigate to the results page by clicking on the search bar and pressing enter
4. click on the new listing button
5. log in
6. go back one page

**Expected behavior**
The user should be able to view and access their account through the dashboard if they login and never refresh the page or click on the home button, the user should be able to navigate the site freely 

The image bellow shows that the dashboard displays the welcome message instead of the account option after the user logged in and backtracked to the main page through the browser.

![loggedin](https://user-images.githubusercontent.com/112367930/235271280-3e4c9e83-0521-4a6a-81dd-161555fd4fe1.png)

**Comment by adsarver** [comment]
I don't think this is a bug with the website itself, but rather how the browser handles cache. If you press the back button it brings you to a cached page on the site rather than updating the data. If you refresh the page it'll show you're logged in.
